version: "3.9"

services:
  db_postgres:
    image: postgres
    container_name: db_postgres_container
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=hidayat
      - POSTGRES_PASSWORD=myPassword
    ports:
      - "5400:5432"
    volumes:
      - ./migration/sql/product.sql:/docker-entrypoint-initdb.d/1001.sql
  golang_rest_api:
    network_mode: "host"
    build: .
